import Head from "next/head";
import { motion } from "framer-motion";
import { useState, useEffect, useRef } from "react";

export default function Home() {
  const [width, setWidth] = useState(0);
  const carouselRef = useRef<HTMLDivElement | null>(null);

  const images = [
    "./assets/1.jpg",
    "./assets/2.jpg",
    "./assets/3.jpg",
    "./assets/4.jpg",
    "./assets/5.jpg",
    "./assets/6.jpg",
  ];

  useEffect(() => {
    if (carouselRef.current) {
      const { scrollWidth, offsetWidth } = carouselRef.current;
      setWidth(scrollWidth - offsetWidth);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Slider with Framer Motion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center">
        <motion.div
          ref={carouselRef}
          whileTap={{ cursor: "grabbing" }}
          className="w-4/5 max-w-5xl cursor-grab overflow-hidden"
        >
          <motion.div
            drag="x"
            dragConstraints={{ right: 0, left: -width }}
            className="flex"
          >
            {images.map((imageSrc, index) => (
              <motion.div
                key={index}
                className="item min-h-[40rem] min-w-[30rem] p-10"
              >
                <picture>
                  <img
                    src={imageSrc}
                    alt="Cat"
                    className="w-full h-full object-cover rounded-3xl pointer-events-none"
                  />
                </picture>
              </motion.div>
            ))}
          </motion.div>
        </motion.div>
      </main>
    </>
  );
}
